import { useState } from 'react';
import { Download, FileText, Loader2 } from 'lucide-react';
import type { FullSafetyResponse } from '@/lib/api';
import type { TravelParams } from '@/types/safety';
import { toast } from 'sonner';

interface ExportReportProps {
  data: FullSafetyResponse;
  locationName: string;
  params: TravelParams;
}

const ExportReport = ({ data, locationName, params }: ExportReportProps) => {
  const [exporting, setExporting] = useState(false);

  const generateTextReport = (): string => {
    const riskLabel =
      data.safetyIndex >= 70 ? 'Generally Safe' : data.safetyIndex >= 40 ? 'Use Caution' : 'High Risk';

    const lines = [
      '╔══════════════════════════════════════╗',
      '║      LUMOS SAFETY REPORT             ║',
      '╚══════════════════════════════════════╝',
      '',
      `Location: ${locationName}`,
      `Date: ${new Date().toLocaleDateString()}`,
      `Time of Travel: ${params.timeOfTravel}`,
      `Group Size: ${params.peopleCount}`,
      '',
      '── SAFETY SCORE ──────────────────────',
      `Score: ${data.safetyIndex}/100 (${riskLabel})`,
      '',
      '── TIME ANALYSIS ─────────────────────',
      `Current Risk: ${data.timeAnalysis.currentRisk}%`,
      `Peak Risk Hours: ${data.timeAnalysis.peakHours}`,
      `Safest Hours: ${data.timeAnalysis.safestHours}`,
      '',
      '── COMMON INCIDENTS ──────────────────',
      ...data.incidentTypes.map(
        (i) => `  ${i.icon} ${i.type}: ${Math.round(i.probability * 100)}%`
      ),
      '',
      '── DATA SOURCES ──────────────────────',
      ...data.dataSources.map(
        (s) => `  • ${s.name} (${s.recordCount.toLocaleString()} records, updated ${s.lastUpdated})`
      ),
      '',
      '── EMERGENCY NUMBERS ─────────────────',
      ...data.emergencyNumbers.map((n) => `  📞 ${n.label}: ${n.number}`),
      '',
      '──────────────────────────────────────',
      'Generated by Lumos — Know Before You Go',
      `https://lumos.app | ${new Date().toISOString()}`,
    ];

    return lines.join('\n');
  };

  const handleExport = async () => {
    setExporting(true);
    try {
      const text = generateTextReport();
      const blob = new Blob([text], { type: 'text/plain;charset=utf-8' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `lumos-report-${locationName.replace(/[^a-zA-Z0-9]/g, '-').toLowerCase()}.txt`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
      toast.success('Report exported!');
    } catch {
      toast.error('Export failed');
    } finally {
      setExporting(false);
    }
  };

  return (
    <button
      onClick={handleExport}
      disabled={exporting}
      className="header-btn flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground transition-colors glass-panel px-2.5 sm:px-3 py-2 rounded-xl disabled:opacity-50 flex-shrink-0"
      title="Export report"
      aria-label="Export safety report"
    >
      {exporting ? (
        <Loader2 className="w-4 h-4 animate-spin" />
      ) : (
        <FileText className="w-4 h-4" />
      )}
    </button>
  );
};

export default ExportReport;
